#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 doftmoon
# put in ~/.local/lib/doftmoon-shell-utils
#
# set of my template commands that I use and like to include in my small scripts
# as it makes it easier to write scripts and follow DRY

SAKURA='\033[38;2;219;184;213m'
RED='\033[0;31m'
NC='\033[0m'

info() {
   if command -v gum &>/dev/null; then
      gum style --foreground 10 "$1"
   else
      echo -e "${SAKURA}INFO:${NC} $1"
   fi
}

warn() {
   if command -v gum &>/dev/null; then
      gum style --foreground 11 "$1"
   else
      echo -e "\e[33mWARNING:${NC} $1"
   fi
}

error() {
   if command -v gum &>/dev/null; then
      gum style --foreground 9 "$1" >&2
   else
      echo -e "${RED}ERROR:${NC} $1" >&2
   fi
   exit 1
}

spiner() {
   if command -v gum &>/dev/null; then
      gum spiner "$@"
   else
      echo -e "$@"
   fi
}

confirm() {
   if command -v gum &>/dev/null; then
      gum confirm "$1"
   else
      echo -n "$1 (y/n): "; read -r r; [[ "$r" =~ [Yy]$ ]]
   fi
}

choose() {
   local prompt="$1"
   shift
   if command -v gum &>/dev/null; then
      gum choose --cursor.foreground 12 --header="$prompt" --header.foreground 12 "$@"
   elif command -v fzf &>/dev/null; then
      printf "%s\n" "$@" |
         fzf --prompt='$prompt' \
            --height=20% \
            --border --cycle
   else
      select opt in "$@"; do [[ -n "$opt" ]] && { echo "$opt"; break; }; done
   fi
}

ensure_not_root() {
   if [[ "$EUID" -eq 0 ]]; then
      error "Don't run as root!"
   fi
}

detect_package_manager() {
   local pkg_manager=''
   local mgrs=(pacman zypper dnf apt)

   if command -v apt-get &>/dev/null; then
      pkg_manager='apt'
   elif command -v pacman &>/dev/null; then
      pkg_manager='pacman'
   elif command -v dnf &>/dev/null; then
      pkg_manager='dnf'
   elif command -v apk &>/dev/null; then
      pkg_manager='apk'
   else
      pkg_manager='unknown'
      error 'Could not detect a known package manager. Aborting.'
   fi

   echo "$pkg_manager"
}
